### ISSUE TITLE
TK3- Subir referencias (sitios web relacionados )

### ISSUE THREAD

**Issue by Gaghyta** [VinoVivo/VinoVivo-Organizacion-Archivos#3]
Subir screenshoots de los componentes que podrían utilizarse

**Comment by ElianaZanelli** [comment]
Encontré una página en donde están diferenciados los vinos en "combos" "vinos tintos" "vinos blancos" vinos rosados" "espumantes" y "accesorios". Me parece que es una buena opción para los filtros. Y lo de los accesorios es algo que no tuvimos en cuenta y estaría bueno agrgar.
![vinos](https://github.com/VinoVivo/VinoVivo-Organizacion-Archivos/assets/93229611/167adfd2-e0f6-4a46-b0df-021c1404a2da)

**Comment by julioborn** [comment]
Siguiendo con esa idea de los filtros, me gustó de esta manera con íconos sencillos. Para que no queden solo cuadrados con texto.
![vinoidea1](https://github.com/VinoVivo/VinoVivo-Organizacion-Archivos/assets/91159152/34193de6-f2ca-40b3-89e4-8534f01496f6)

**Comment by julioborn** [comment]
Tambén está buena la idea de que haya filtros laterales desplegables como en esta página.
![vinoidea2](https://github.com/VinoVivo/VinoVivo-Organizacion-Archivos/assets/91159152/c0c6ffab-3fe6-4b90-a459-52398ac390d1)
![vinoidea3](https://github.com/VinoVivo/VinoVivo-Organizacion-Archivos/assets/91159152/258a2f5f-6288-43e2-a180-d8428b6ea2fe)

**Comment by Sol-Zito** [comment]
Siguiendo el hilo de filtros vi este sitio web donde lo filtran por tipo de vino, marca y precio
![Screenshot 2024-05-06 125435](https://github.com/VinoVivo/VinoVivo-Organizacion-Archivos/assets/93354522/ae36e39a-6371-46b2-ac28-81318cf06bd6)

https://www.lodegranado.com.ar/vinos/

**Comment by Sol-Zito** [comment]
Este por ejemplo, tiene mas filtro e inlcuso tiene un filtro de maridaje, que lo podriamos sumar tomando la idea de Carla en lo que seria Nosotros que es donde se muestran las catas y maridajes. 
![image](https://github.com/VinoVivo/VinoVivo-Organizacion-Archivos/assets/93354522/c3334347-318b-4f89-b206-83670d11495a)
https://viners.com.ar/collections/vinos

**Comment by julioborn** [comment]
Si, para mi está bueno tener esos filtros laterales
